language: php

env:
  - OPCODE_CACHE=apc

services:
  - redis-server

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

install:
  - composer self-update
  - composer update

script:
  - phpunit --group default,integrationTest
